// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(ECommerceContext))]
    [Migration("20251210124407_DummyData")]
    partial class DummyData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("WebAPI.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is a sample product description.",
                            ImageUrl = "https://example.com/sample-product-1.jpg",
                            IsActive = true,
                            Name = "Sample Product 1",
                            Price = 19.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is another sample product description.",
                            ImageUrl = "https://example.com/sample-product-2.jpg",
                            IsActive = true,
                            Name = "Sample Product 2",
                            Price = 29.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            Description = "This is yet another sample product description.",
                            ImageUrl = "https://example.com/sample-product-3.jpg",
                            IsActive = true,
                            Name = "Sample Product 3",
                            Price = 9.99m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 4,
                            Description = "This is a fourth sample product description.",
                            ImageUrl = "https://example.com/sample-product-4.jpg",
                            IsActive = true,
                            Name = "Sample Product 4",
                            Price = 49.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 5,
                            Description = "This is a fifth sample product description.",
                            ImageUrl = "https://example.com/sample-product-5.jpg",
                            IsActive = false,
                            Name = "Sample Product 5",
                            Price = 15.99m,
                            Stock = 150
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
